import '@global/styles/normalize.scss'

import { rubik, nunito } from '@/global/fonts'
import { Metadata } from 'next'
import clsx from 'clsx'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={clsx(rubik.variable, nunito.variable)}>{children}</body>
    </html>
  )
}
